<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ValueItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('value_items')->delete();
	    DB::table('value_items')->insert([
            'id'			=> 74,
		'product_code' => 'CSH',
            'product_code_new' => 'CSH',
            'currency_code' => 'EUR',
            'currency_code_new' => 'EUR',
            'denom_value' => 5,
            'denom_value_new' => 5,
            'cassette_fit' => TRUE,
            'cassette_fit_new' => TRUE,
            'column_fit' => TRUE,
            'column_fit_new' => TRUE,
            'balance_interval' => 5,
            'balance_interval_new' => 5,
            'column_trigger' => 0,
            'column_trigger_new' => 0,
            'column_additional' => 0,
            'column_additional_new' => 0,
            'cassette_min' => 40,
            'cassette_min_new' => 40,
            'cassette_trigger' => 40,
            'cassette_trigger_new' => 40,
            'cassette_additional' => 1700,
            'cassette_additional_new' => 1700,
            'last_balanced_at' => '2016-07-11 19:07:39.663905+01',
            'last_balanced_by_user_id' => 57,
            'created_at' => '2014-08-18 13:11:18.286054+01',
            'created_by_user_id' => 1,
            'updated_at' => '2016-06-21 15:18:27.787469+01',
            'updated_by_user_id' => 14,
            'verified_at' => '2016-06-21 15:40:31.33007+01',
            'verified_by_user_id' => 1,
            'enabled' => TRUE,
            'enabled_new' => TRUE,
            'lock_version' => 25,
            'cassette_algorithm' => 'Adaptive',
            'cassette_algorithm_new' => 'Adaptive',
            'column_algorithm' => 'Maximize',
            'column_algorithm_new' => 'Maximize',
            'verification_state' => 'Synchronised',
	    ]);
	    DB::table('value_items')->insert([
            'id'			=> 75,
		'product_code' => 'CSH',
            'product_code_new' => 'CSH',
            'currency_code' => 'EUR',
            'currency_code_new' => 'EUR',
            'denom_value' => 10,
            'denom_value_new' => 10,
            'cassette_fit' => TRUE,
            'cassette_fit_new' => TRUE,
            'column_fit' => TRUE,
            'column_fit_new' => TRUE,
            'balance_interval' => 5,
            'balance_interval_new' => 5,
            'column_trigger' => 0,
            'column_trigger_new' => 0,
            'column_additional' => 0,
            'column_additional_new' => 0,
            'cassette_min' => 40,
            'cassette_min_new' => 40,
            'cassette_trigger' => 40,
            'cassette_trigger_new' => 40,
            'cassette_additional' => 0,
            'cassette_additional_new' => 0,
            'last_balanced_at' => '2016-07-11 19:07:39.663905+01',
            'last_balanced_by_user_id' => 57,
            'created_at' => '2014-08-18 13:11:18.286054+01',
            'created_by_user_id' => 1,
            'updated_at' => '2016-06-21 15:19:17.23606+01',
            'updated_by_user_id' => 14,
            'verified_at' => '2016-06-21 15:40:31.33007+01',
            'verified_by_user_id' => 1,
            'enabled' => TRUE,
            'enabled_new' => TRUE,
            'lock_version' => 26,
            'cassette_algorithm' => 'Maximize',
            'cassette_algorithm_new' => 'Maximize',
            'column_algorithm' => 'Maximize',
            'column_algorithm_new' => 'Maximize',
            'verification_state' => 'Synchronised',
	    ]);
	    DB::table('value_items')->insert([
            'id'			=> 76,
		'product_code' => 'CSH',
            'product_code_new' => 'CSH',
            'currency_code' => 'EUR',
            'currency_code_new' => 'EUR',
            'denom_value' => 20,
            'denom_value_new' => 20,
            'cassette_fit' => TRUE,
            'cassette_fit_new' => TRUE,
            'column_fit' => TRUE,
            'column_fit_new' => TRUE,
            'balance_interval' => 5,
            'balance_interval_new' => 5,
            'column_trigger' => 0,
            'column_trigger_new' => 0,
            'column_additional' => 0,
            'column_additional_new' => 0,
            'cassette_min' => 40,
            'cassette_min_new' => 40,
            'cassette_trigger' => 40,
            'cassette_trigger_new' => 40,
            'cassette_additional' => 0,
            'cassette_additional_new' => 0,
            'last_balanced_at' => '2016-07-11 19:07:39.663905+01',
            'last_balanced_by_user_id' => 44,
            'created_at' => '2014-08-18 13:11:18.286054+01',
            'created_by_user_id' => 1,
            'updated_at' => '2016-06-21 15:19:31.756041+01',
            'updated_by_user_id' => 14,
            'verified_at' => '2016-06-21 15:40:31.33007+01',
            'verified_by_user_id' => 1,
            'enabled' => TRUE,
            'enabled_new' => TRUE,
            'lock_version' => 26,
            'cassette_algorithm' => 'Maximize',
            'cassette_algorithm_new' => 'Maximize',
            'column_algorithm' => 'Maximize',
            'column_algorithm_new' => 'Maximize',
            'verification_state' => 'Synchronised',
	    ]);
	    DB::table('value_items')->insert([
            'id'			=> 77,
		'product_code' => 'CSH',
            'product_code_new' => 'CSH',
            'currency_code' => 'EUR',
            'currency_code_new' => 'EUR',
            'denom_value' => 50,
            'denom_value_new' => 50,
            'cassette_fit' => TRUE,
            'cassette_fit_new' => TRUE,
            'column_fit' => TRUE,
            'column_fit_new' => TRUE,
            'balance_interval' => 5,
            'balance_interval_new' => 5,
            'column_trigger' => 0,
            'column_trigger_new' => 0,
            'column_additional' => 0,
            'column_additional_new' => 0,
            'cassette_min' => 40,
            'cassette_min_new' => 40,
            'cassette_trigger' => 40,
            'cassette_trigger_new' => 40,
            'cassette_additional' => 0,
            'cassette_additional_new' => 0,
            'last_balanced_at' => '2016-07-11 19:07:39.663905+01',
            'last_balanced_by_user_id' => 137,
            'created_at' => '2014-08-18 13:11:18.286054+01',
            'created_by_user_id' => 1,
            'updated_at' => '2016-06-21 15:19:45.124577+01',
            'updated_by_user_id' => 14,
            'verified_at' => '2016-06-21 15:40:31.33007+01',
            'verified_by_user_id' => 1,
            'enabled' => TRUE,
            'enabled_new' => TRUE,
            'lock_version' => 23,
            'cassette_algorithm' => 'Maximize',
            'cassette_algorithm_new' => 'Maximize',
            'column_algorithm' => 'Maximize',
            'column_algorithm_new' => 'Maximize',
            'verification_state' => 'Synchronised',
	    ]);
	    DB::table('value_items')->insert([
            'id'			=> 78,
		'product_code' => 'CSH',
            'product_code_new' => 'CSH',
            'currency_code' => 'EUR',
            'currency_code_new' => 'EUR',
            'denom_value' => 100,
            'denom_value_new' => 100,
            'cassette_fit' => TRUE,
            'cassette_fit_new' => TRUE,
            'column_fit' => TRUE,
            'column_fit_new' => TRUE,
            'balance_interval' => 5,
            'balance_interval_new' => 5,
            'column_trigger' => 0,
            'column_trigger_new' => 0,
            'column_additional' => 500,
            'column_additional_new' => 500,
            'cassette_min' => 40,
            'cassette_min_new' => 40,
            'cassette_trigger' => 40,
            'cassette_trigger_new' => 40,
            'cassette_additional' => 200,
            'cassette_additional_new' => 200,
            'last_balanced_at' => '2016-07-11 19:07:39.663905+01',
            'last_balanced_by_user_id' => 97,
            'created_at' => '2014-08-18 13:11:18.286054+01',
            'created_by_user_id' => 1,
            'updated_at' => '2016-06-28 16:30:41.992105+01',
            'updated_by_user_id' => 29,
            'verified_at' => '2016-06-28 16:31:28.859424+01',
            'verified_by_user_id' => 145,
            'enabled' => TRUE,
            'enabled_new' => TRUE,
            'lock_version' => 25,
            'cassette_algorithm' => 'Adaptive',
            'cassette_algorithm_new' => 'Adaptive',
            'column_algorithm' => 'Adaptive',
            'column_algorithm_new' => 'Adaptive',
            'verification_state' => 'Synchronised',
	    ]);
	    DB::table('value_items')->insert([
            'id'			=> 79,
		'product_code' => 'CSH',
            'product_code_new' => 'CSH',
            'currency_code' => 'EUR',
            'currency_code_new' => 'EUR',
            'denom_value' => 200,
            'denom_value_new' => 200,
            'cassette_fit' => TRUE,
            'cassette_fit_new' => TRUE,
            'column_fit' => TRUE,
            'column_fit_new' => TRUE,
            'balance_interval' => 5,
            'balance_interval_new' => 5,
            'column_trigger' => 0,
            'column_trigger_new' => 0,
            'column_additional' => 100,
            'column_additional_new' => 100,
            'cassette_min' => 40,
            'cassette_min_new' => 40,
            'cassette_trigger' => 40,
            'cassette_trigger_new' => 40,
            'cassette_additional' => 0,
            'cassette_additional_new' => 0,
            'last_balanced_at' => '2016-07-11 19:07:39.663905+01',
            'last_balanced_by_user_id' => 97,
            'created_at' => '2014-08-18 13:11:18.286054+01',
            'created_by_user_id' => 1,
            'updated_at' => '2016-06-21 15:22:17.709544+01',
            'updated_by_user_id' => 14,
            'verified_at' => '2016-06-21 15:40:31.33007+01',
            'verified_by_user_id' => 1,
            'enabled' => TRUE,
            'enabled_new' => TRUE,
            'lock_version' => 19,
            'cassette_algorithm' => 'Required',
            'cassette_algorithm_new' => 'Required',
            'column_algorithm' => 'Adaptive',
            'column_algorithm_new' => 'Adaptive',
            'verification_state' => 'Synchronised',
	    ]);
    }
}
			